# Olist E-Commerce Dataset — Exploratory Data Analysis

This notebook explores the Brazilian E-Commerce Public Dataset by Olist.

## Objectives

- Understand the source datasets
- Identify table grain
- Identify primary and foreign keys
- Analyze data types
- Identify missing values
- Investigate relationships between tables
- Identify data quality issues
- Generate initial business insights

In [1]:
## 1. Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

pd.__version__

'2.3.3'

In [ ]:
DATA_DIR = Path("../data")
OUTPUT_DIR = Path("../outputs/eda")

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

In [3]:
## 2. Load datasets

tables = {
    "customers": pd.read_csv(DATA_DIR / "olist_customers_dataset.csv"),
    "orders": pd.read_csv(DATA_DIR / "olist_orders_dataset.csv"),
    "order_items": pd.read_csv(DATA_DIR / "olist_order_items_dataset.csv"),
    "payments": pd.read_csv(DATA_DIR / "olist_order_payments_dataset.csv"),
    "reviews": pd.read_csv(DATA_DIR / "olist_order_reviews_dataset.csv"),
    "products": pd.read_csv(DATA_DIR / "olist_products_dataset.csv"),
    "sellers": pd.read_csv(DATA_DIR / "olist_sellers_dataset.csv"),
    "geolocation": pd.read_csv(DATA_DIR / "olist_geolocation_dataset.csv"),
    "category_translation": pd.read_csv(
        DATA_DIR / "product_category_name_translation.csv"
    ),
}

tables.keys()

dict_keys(['customers', 'orders', 'order_items', 'payments', 'reviews', 'products', 'sellers', 'geolocation', 'category_translation'])

In [4]:
## 3. Dataset overview
table_summary = pd.DataFrame({
    table_name: {
        "rows": df.shape[0],
        "columns": df.shape[1]
    }
    for table_name, df in tables.items()
}).T

table_summary

                         rows  columns
customers               99441        5
orders                  99441        8
order_items            112650        7
payments               103886        5
reviews                 99224        7
products                32951        9
sellers                  3095        4
geolocation           1000163        5
category_translation       71        2

In [5]:
table_summary.to_csv(OUTPUT_DIR / "table_summary.csv")

In [7]:
#inspect the schema
# for name, df in tables.items():
#     print("=" * 70)
#     print(name)
#     print("=" * 70)
#     print(df.info())

# for name, df in tables.items():
#     print(name)
#     print(df.columns.tolist())
#     print()

for name, df in tables.items():
    print("=" * 70)
    print(name)
    print("=" * 70)
    print(df.info())
    print("Columns:", df.columns.tolist())
    print()

======================================================================
customers
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB
None
Columns: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

======================================================================
orders
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB
None
Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

======================================================================
order_items
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB
None
Columns: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

======================================================================
payments
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB
None
Columns: ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

======================================================================
reviews
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB
None
Columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

======================================================================
products
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB
None
Columns: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

======================================================================
sellers
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB
None
Columns: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

======================================================================
geolocation
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB
None
Columns: ['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

======================================================================
category_translation
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB
None
Columns: ['product_category_name', 'product_category_name_english']

In [8]:
#datatypes
column_profile = []

for table_name, df in tables.items():
    for column in df.columns:
        column_profile.append({
            "table": table_name,
            "column": column,
            "dtype": str(df[column].dtype),
            "null_count": df[column].isna().sum(),
            "null_pct": df[column].isna().mean() * 100,
            "unique_count": df[column].nunique()
        })

column_profile = pd.DataFrame(column_profile)

column_profile.head()

,table,column,dtype,null_count,null_pct,unique_count
0,customers,customer_id,object,0,0.0,99441
1,customers,customer_unique_id,object,0,0.0,96096
2,customers,customer_zip_code_prefix,int64,0,0.0,14994
3,customers,customer_city,object,0,0.0,4119
4,customers,customer_state,object,0,0.0,27

In [9]:
column_profile.to_csv(
    OUTPUT_DIR / "column_profiling.csv",
    index=False
)

In [10]:
#Missing values analysis
missing_values = []

for table_name, df in tables.items():
    for column in df.columns:
        null_count = df[column].isna().sum()

        if null_count > 0:
            missing_values.append({
                "table": table_name,
                "column": column,
                "null_count": null_count,
                "null_pct": round(
                    null_count / len(df) * 100,
                    2
                )
            })

missing_values = pd.DataFrame(missing_values)

missing_values.sort_values(
    "null_pct",
    ascending=False
)

       table                         column  null_count  null_pct
3    reviews           review_comment_title       87656     88.34
4    reviews         review_comment_message       58247     58.70
2     orders  order_delivered_customer_date        2965      2.98
6   products            product_name_lenght         610      1.85
5   products          product_category_name         610      1.85
7   products     product_description_lenght         610      1.85
8   products             product_photos_qty         610      1.85
1     orders   order_delivered_carrier_date        1783      1.79
0     orders              order_approved_at         160      0.16
9   products               product_weight_g           2      0.01
10  products              product_length_cm           2      0.01
11  products              product_height_cm           2      0.01
12  products               product_width_cm           2      0.01

In [11]:
missing_values.to_csv(
    OUTPUT_DIR / "missing_values.csv",
    index=False
)

In [12]:
#duplicate analysis - complete-row duplicates:
duplicate_analysis = []

for table_name, df in tables.items():
    duplicate_analysis.append({
        "table": table_name,
        "duplicate_rows": df.duplicated().sum(),
        "duplicate_pct": round(
            df.duplicated().mean() * 100,
            2
        )
    })

duplicate_analysis = pd.DataFrame(duplicate_analysis)

duplicate_analysis

                  table  duplicate_rows  duplicate_pct
0             customers               0           0.00
1                orders               0           0.00
2           order_items               0           0.00
3              payments               0           0.00
4               reviews               0           0.00
5              products               0           0.00
6               sellers               0           0.00
7           geolocation          261831          26.18
8  category_translation               0           0.00

In [ ]:
duplicate_analysis.to_csv(
    OUTPUT_DIR / "duplicate_analysis.csv",
    index=False
)

In [14]:
#Verify primary key

customers = tables["customers"]
customers["customer_id"].is_unique

orders = tables["orders"]
orders["order_id"].is_unique

products= tables["products"]
products["product_id"].is_unique

sellers = tables["sellers"]
sellers["seller_id"].is_unique

order_items= tables["order_items"]
order_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

payments= tables["payments"]
payments.duplicated(
    subset=["order_id", "payment_sequential"]
).sum()

reviews= tables["reviews"]
reviews.duplicated(
    subset=["order_id", "review_id"]
).sum()

np.int64(0)