In [12]:
query = """
SELECT *
FROM `olist-data-pipeline-507001.olist_mart.fact_orders`
LIMIT 5
"""

orders_sample = pd.read_sql(query, engine)

orders_sample.head()

,order_key,order_id,customer_key,order_date_key,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,1117e36e0a1ee753c965c03c634fc8be,809a282bbd5dbcabb6f2f724fca862ec,cd73193746a0e87dfdadb483d0d6cf29,20160913,CANCELED,2016-09-13 15:24:19+00:00,2016-10-07 13:16:46+00:00,NaT,NaT,2016-09-30 00:00:00+00:00
1,011d365db07b4f01977880a3ddb6a2c7,bfbd0f9bdef84302105ad712db648a6c,4b8ae60e4bd0512b27cfd71253443d54,20160915,DELIVERED,2016-09-15 12:16:38+00:00,2016-09-15 12:16:38+00:00,2016-11-07 17:11:53+00:00,2016-11-09 07:47:38+00:00,2016-10-04 00:00:00+00:00
2,9b06d3646818e932663482502d34d8c4,2e7a8482f6fb09756ca50c10d7bfc047,cf899313ee99e395c9e565e4d8b5d653,20160904,SHIPPED,2016-09-04 21:15:19+00:00,2016-10-07 13:18:03+00:00,2016-10-18 13:14:51+00:00,NaT,2016-10-20 00:00:00+00:00
3,a64175cc5ddde762ac3b57d690b38cd9,e5215415bb6f76fe3b7cb68103a0d1c0,4f327a6e7a40fd6fb62df926c9d9acde,20161022,CANCELED,2016-10-22 08:25:27+00:00,NaT,NaT,NaT,2016-10-24 00:00:00+00:00
4,6af58056fe4c8fe1eed1b8eefd82c2d9,71303d7e93b399f5bcd537d124c0bcfa,4084a255b7441ebca007a5313e088274,20161002,CANCELED,2016-10-02 22:07:52+00:00,2016-10-06 15:50:56+00:00,NaT,NaT,2016-10-25 00:00:00+00:00

In [13]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("bigquery://olist-data-pipeline-507001")

In [14]:
query = """
SELECT
    DATE(o.order_purchase_timestamp) AS sales_date,
    SUM(oi.price) AS total_sales
FROM `olist-data-pipeline-507001.olist_mart.fact_orders` o
JOIN `olist-data-pipeline-507001.olist_mart.fact_order_items` oi
    ON o.order_key = oi.order_key
WHERE o.order_status = 'DELIVERED'
GROUP BY sales_date
ORDER BY sales_date
"""

daily_sales = pd.read_sql(query, engine)

daily_sales.head()

/home/nivedha/miniconda3/lib/python3.14/site-packages/google/cloud/bigquery/client.py:623: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  warnings.warn(

   sales_date  total_sales
0  2016-09-15       134.97
1  2016-10-03       441.98
2  2016-10-04      8595.89
3  2016-10-05      6169.77
4  2016-10-06      5889.96

In [15]:
query = """
SELECT
    MIN(DATE(order_purchase_timestamp)) AS first_date,
    MAX(DATE(order_purchase_timestamp)) AS last_date
FROM `olist-data-pipeline-507001.olist_mart.fact_orders`
"""

date_range = pd.read_sql(query, engine)

date_range

   first_date   last_date
0  2016-09-04  2018-10-17

In [16]:
query = """
SELECT table_name
FROM `olist-data-pipeline-507001.olist_mart.INFORMATION_SCHEMA.TABLES`
ORDER BY table_name
"""

tables = pd.read_sql(query, engine)

tables

         table_name
0      dim_customer
1          dim_date
2   dim_geolocation
3       dim_product
4        dim_seller
5  fact_order_items
6       fact_orders
7     fact_payments
8      fact_reviews
9  fct_customer_rfm

In [18]:
query = """
SELECT table_name
FROM `olist-data-pipeline-507001.olist_raw.INFORMATION_SCHEMA.TABLES`
ORDER BY table_name
"""

tables = pd.read_sql(query, engine)

tables

                    table_name
0     raw_category_translation
1                raw_customers
2      raw_geolocation_dataset
3            raw_holidays_2017
4            raw_holidays_2018
5              raw_order_items
6   raw_order_payments_dataset
7    raw_order_reviews_dataset
8                   raw_orders
9                 raw_products
10                 raw_sellers

In [20]:
query = """
SELECT
    table_schema,
    table_name
FROM `olist-data-pipeline-507001.region-us.INFORMATION_SCHEMA.TABLES`
WHERE LOWER(table_name) LIKE '%holiday%'
ORDER BY table_schema, table_name
"""

holiday_tables = pd.read_sql(query, engine)
holiday_tables

    table_schema            table_name
0      olist_raw     raw_holidays_2017
1      olist_raw     raw_holidays_2018
2  olist_staging     raw_holidays_2017
3  olist_staging     raw_holidays_2018
4  olist_staging  stg_holiday_calendar

In [21]:
query = """
SELECT *
FROM `olist-data-pipeline-507001.olist_staging.stg_holiday_calendar`
"""

holidays = pd.read_sql(query, engine)
holidays

      hol_date                  hol_name  hol_type        hol_day
0   2017-01-01  CONFRATERNIZAÇÃO MUNDIAL  NATIONAL        DOMINGO
1   2017-04-16                    PÁSCOA  NATIONAL        DOMINGO
2   2017-11-15  PROCLAMAÇÃO DA REPÚBLICA  NATIONAL   QUARTA-FEIRA
3   2017-11-02                   FINADOS  NATIONAL   QUINTA-FEIRA
4   2017-10-12   NOSSA SENHORA APARECIDA  NATIONAL   QUINTA-FEIRA
5   2017-06-15            CORPUS CHRISTI  NATIONAL   QUINTA-FEIRA
6   2017-09-07   INDEPENDÊNCIA DO BRASIL  NATIONAL   QUINTA-FEIRA
7   2017-02-27                  CARNAVAL  NATIONAL  SEGUNDA-FEIRA
8   2017-05-01           DIA DO TRABALHO  NATIONAL  SEGUNDA-FEIRA
9   2017-12-25                     NATAL  NATIONAL  SEGUNDA-FEIRA
10  2017-04-14         SEXTA-FEIRA SANTA  NATIONAL    SEXTA-FEIRA
11  2017-04-21                TIRADENTES  NATIONAL    SEXTA-FEIRA
12  2017-02-28                  CARNAVAL  NATIONAL    TERÇA-FEIRA
13  2018-01-01  CONFRATERNIZAÇÃO MUNDIAL  NATIONAL  SEGUNDA-FEIRA
14  2018-02-12                  CARNAVAL  NATIONAL  SEGUNDA-FEIRA
15  2018-03-30         SEXTA-FEIRA SANTA  NATIONAL    SEXTA-FEIRA
16  2018-02-13                  CARNAVAL  NATIONAL    TERÇA-FEIRA
17  2018-04-01                    PÁSCOA  NATIONAL        DOMINGO
18  2018-11-15  PROCLAMAÇÃO DA REPÚBLICA  NATIONAL   QUINTA-FEIRA
19  2018-05-31            CORPUS CHRISTI  NATIONAL   QUINTA-FEIRA
20  2018-11-02                   FINADOS  NATIONAL    SEXTA-FEIRA
21  2018-09-07   INDEPENDÊNCIA DO BRASIL  NATIONAL    SEXTA-FEIRA
22  2018-10-12   NOSSA SENHORA APARECIDA  NATIONAL    SEXTA-FEIRA
23  2018-04-21                TIRADENTES  NATIONAL         SÁBADO
24  2018-05-01           DIA DO TRABALHO  NATIONAL    TERÇA-FEIRA
25  2018-12-25                     NATAL  NATIONAL    TERÇA-FEIRA

In [22]:
holidays.head()

     hol_date                  hol_name  hol_type       hol_day
0  2017-01-01  CONFRATERNIZAÇÃO MUNDIAL  NATIONAL       DOMINGO
1  2017-04-16                    PÁSCOA  NATIONAL       DOMINGO
2  2017-11-15  PROCLAMAÇÃO DA REPÚBLICA  NATIONAL  QUARTA-FEIRA
3  2017-11-02                   FINADOS  NATIONAL  QUINTA-FEIRA
4  2017-10-12   NOSSA SENHORA APARECIDA  NATIONAL  QUINTA-FEIRA

In [25]:
holidays["hol_date"].min(), holidays["hol_date"].max()

daily_sales["sales_date"].dtype, holidays["hol_date"].dtype

daily_sales["sales_date"] = pd.to_datetime(daily_sales["sales_date"])
holidays["hol_date"] = pd.to_datetime(holidays["hol_date"])

In [26]:
sales_holidays = daily_sales.merge(
    holidays,
    left_on="sales_date",
    right_on="hol_date",
    how="left"
)

sales_holidays.head()

  sales_date  total_sales hol_date hol_name hol_type hol_day
0 2016-09-15       134.97      NaT      NaN      NaN     NaN
1 2016-10-03       441.98      NaT      NaN      NaN     NaN
2 2016-10-04      8595.89      NaT      NaN      NaN     NaN
3 2016-10-05      6169.77      NaT      NaN      NaN     NaN
4 2016-10-06      5889.96      NaT      NaN      NaN     NaN

In [27]:
sales_holidays["is_holiday"] = sales_holidays["hol_name"].notna()

sales_holidays.head()

  sales_date  total_sales hol_date hol_name hol_type hol_day  is_holiday
0 2016-09-15       134.97      NaT      NaN      NaN     NaN       False
1 2016-10-03       441.98      NaT      NaN      NaN     NaN       False
2 2016-10-04      8595.89      NaT      NaN      NaN     NaN       False
3 2016-10-05      6169.77      NaT      NaN      NaN     NaN       False
4 2016-10-06      5889.96      NaT      NaN      NaN     NaN       False

In [28]:
sales_holidays[sales_holidays["is_holiday"] == True].head(10)

,sales_date,total_sales,hol_date,hol_name,hol_type,hol_day,is_holiday
63,2017-02-27,5764.32,2017-02-27,CARNAVAL,NATIONAL,SEGUNDA-FEIRA,True
64,2017-02-28,10701.76,2017-02-28,CARNAVAL,NATIONAL,TERÇA-FEIRA,True
109,2017-04-14,6704.19,2017-04-14,SEXTA-FEIRA SANTA,NATIONAL,SEXTA-FEIRA,True
111,2017-04-16,5025.96,2017-04-16,PÁSCOA,NATIONAL,DOMINGO,True
116,2017-04-21,8426.27,2017-04-21,TIRADENTES,NATIONAL,SEXTA-FEIRA,True
126,2017-05-01,11786.89,2017-05-01,DIA DO TRABALHO,NATIONAL,SEGUNDA-FEIRA,True
171,2017-06-15,12079.87,2017-06-15,CORPUS CHRISTI,NATIONAL,QUINTA-FEIRA,True
255,2017-09-07,16893.50,2017-09-07,INDEPENDÊNCIA DO BRASIL,NATIONAL,QUINTA-FEIRA,True
290,2017-10-12,18352.08,2017-10-12,NOSSA SENHORA APARECIDA,NATIONAL,QUINTA-FEIRA,True
311,2017-11-02,21074.93,2017-11-02,FINADOS,NATIONAL,QUINTA-FEIRA,True

In [29]:
sales_holidays.groupby("is_holiday")["total_sales"].mean()

is_holiday
False    21778.31674
True     16436.73000
Name: total_sales, dtype: float64

In [30]:
sales_holidays["is_holiday"].value_counts()

is_holiday
False    592
True      20
Name: count, dtype: int64

In [31]:
sales_holidays[sales_holidays["is_holiday"] == True][
    ["sales_date", "hol_name", "total_sales"]
].sort_values("total_sales")

    sales_date                  hol_name  total_sales
111 2017-04-16                    PÁSCOA      5025.96
63  2017-02-27                  CARNAVAL      5764.32
109 2017-04-14         SEXTA-FEIRA SANTA      6704.19
371 2018-01-01  CONFRATERNIZAÇÃO MUNDIAL      6818.31
116 2017-04-21                TIRADENTES      8426.27
364 2017-12-25                     NATAL      9858.64
64  2017-02-28                  CARNAVAL     10701.76
126 2017-05-01           DIA DO TRABALHO     11786.89
171 2017-06-15            CORPUS CHRISTI     12079.87
255 2017-09-07   INDEPENDÊNCIA DO BRASIL     16893.50
290 2017-10-12   NOSSA SENHORA APARECIDA     18352.08
481 2018-04-21                TIRADENTES     18839.36
311 2017-11-02                   FINADOS     21074.93
459 2018-03-30         SEXTA-FEIRA SANTA     21871.83
324 2017-11-15  PROCLAMAÇÃO DA REPÚBLICA     22591.40
414 2018-02-13                  CARNAVAL     23059.65
413 2018-02-12                  CARNAVAL     23255.73
521 2018-05-31            CORPUS CHRISTI     24381.28
461 2018-04-01                    PÁSCOA     28553.63
491 2018-05-01           DIA DO TRABALHO     32695.00

In [32]:
holiday_sales = (
    sales_holidays[sales_holidays["is_holiday"] == True]
    .groupby("hol_name")["total_sales"]
    .agg(["mean", "min", "max", "count"])
    .sort_values("mean")
)

holiday_sales

                               mean       min       max  count
hol_name
CONFRATERNIZAÇÃO MUNDIAL   6818.310   6818.31   6818.31      1
NATAL                      9858.640   9858.64   9858.64      1
TIRADENTES                13632.815   8426.27  18839.36      2
SEXTA-FEIRA SANTA         14288.010   6704.19  21871.83      2
CARNAVAL                  15695.365   5764.32  23255.73      4
PÁSCOA                    16789.795   5025.96  28553.63      2
INDEPENDÊNCIA DO BRASIL   16893.500  16893.50  16893.50      1
CORPUS CHRISTI            18230.575  12079.87  24381.28      2
NOSSA SENHORA APARECIDA   18352.080  18352.08  18352.08      1
FINADOS                   21074.930  21074.93  21074.93      1
DIA DO TRABALHO           22240.945  11786.89  32695.00      2
PROCLAMAÇÃO DA REPÚBLICA  22591.400  22591.40  22591.40      1

In [33]:
#Are holiday sales lower because it is a holiday, or because holidays happen to fall on days when sales are normally lower?
daily_sales["day_of_week"] = daily_sales["sales_date"].dt.day_name()

weekday_sales = (
    daily_sales
    .groupby("day_of_week")["total_sales"]
    .mean()
    .sort_values()
)

weekday_sales

day_of_week
Saturday     16828.156322
Sunday       17766.069655
Friday       21710.183182
Thursday     22256.823750
Wednesday    23580.847241
Tuesday      24393.845057
Monday       24646.654659
Name: total_sales, dtype: float64

In [37]:
sales_holidays["day_of_week"] = sales_holidays["sales_date"].dt.day_name()

In [38]:
holiday_comparison = sales_holidays[sales_holidays["is_holiday"] == True].copy()

holiday_comparison["normal_weekday_sales"] = (
    holiday_comparison["day_of_week"].map(weekday_sales)
)

holiday_comparison["sales_difference"] = (
    holiday_comparison["total_sales"]
    - holiday_comparison["normal_weekday_sales"]
)

holiday_comparison[
    ["sales_date", "hol_name", "day_of_week",
     "total_sales", "normal_weekday_sales", "sales_difference"]
].sort_values("sales_difference")

,sales_date,hol_name,day_of_week,total_sales,normal_weekday_sales,sales_difference
63,2017-02-27,CARNAVAL,Monday,5764.32,24646.654659,-18882.334659
371,2018-01-01,CONFRATERNIZAÇÃO MUNDIAL,Monday,6818.31,24646.654659,-17828.344659
109,2017-04-14,SEXTA-FEIRA SANTA,Friday,6704.19,21710.183182,-15005.993182
364,2017-12-25,NATAL,Monday,9858.64,24646.654659,-14788.014659
64,2017-02-28,CARNAVAL,Tuesday,10701.76,24393.845057,-13692.085057
116,2017-04-21,TIRADENTES,Friday,8426.27,21710.183182,-13283.913182
126,2017-05-01,DIA DO TRABALHO,Monday,11786.89,24646.654659,-12859.764659
111,2017-04-16,PÁSCOA,Sunday,5025.96,17766.069655,-12740.109655
171,2017-06-15,CORPUS CHRISTI,Thursday,12079.87,22256.823750,-10176.953750
255,2017-09-07,INDEPENDÊNCIA DO BRASIL,Thursday,16893.50,22256.823750,-5363.323750
290,2017-10-12,NOSSA SENHORA APARECIDA,Thursday,18352.08,22256.823750,-3904.743750
413,2018-02-12,CARNAVAL,Monday,23255.73,24646.654659,-1390.924659
414,2018-02-13,CARNAVAL,Tuesday,23059.65,24393.845057,-1334.195057
311,2017-11-02,FINADOS,Thursday,21074.93,22256.823750,-1181.893750
324,2017-11-15,PROCLAMAÇÃO DA REPÚBLICA,Wednesday,22591.40,23580.847241,-989.447241
459,2018-03-30,SEXTA-FEIRA SANTA,Friday,21871.83,21710.183182,161.646818
481,2018-04-21,TIRADENTES,Saturday,18839.36,16828.156322,2011.203678
521,2018-05-31,CORPUS CHRISTI,Thursday,24381.28,22256.823750,2124.456250
491,2018-05-01,DIA DO TRABALHO,Tuesday,32695.00,24393.845057,8301.154943
461,2018-04-01,PÁSCOA,Sunday,28553.63,17766.069655,10787.560345